# Compose file for developing
version: "3"

services:
  db:
    image: postgres:latest
    container_name: chat_ai_db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=$PSQL_DB_NAME
      - POSTGRES_USER=$PSQL_USER
      - POSTGRES_PASSWORD=$PSQL_PASSWORD
    networks:
      - chat_ai_net

  
  adminer:
    image: adminer:latest
    container_name: chat_ai_adminer
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - chat_ai_net
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}


  backend:
    build: ./backend/
    container_name: chat_ai_backend
    volumes:
      - db:/var/lib/postgresql/data
      - ./backend/:/backend/
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - chat_ai_net
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}


networks:
  chat_ai_net:

volumes:
  db:
